import os
import pandas as pd
import glob

def escape_tex(text):
    return str(text).replace('_', '\\_') if pd.notnull(text) else ""

def generate_report():
    out_file = "report.tex"
    # Using the more complete CSV generated by calculate_galfit_inclination.py
    df = pd.read_csv("galfit_inc_angle.csv")
    df_psf = pd.read_csv("psf_fwhm_summary.csv")
    
    with open(out_file, "w") as f:
        # Preamble
        f.write(r"""\documentclass[a4paper,11pt]{article}
\usepackage{graphicx}
\usepackage{geometry}
\usepackage{float}
\usepackage{amsmath}
\usepackage{hyperref}
\usepackage{subcaption}
\usepackage{booktabs}
\usepackage{adjustbox}
\usepackage{xcolor}
\usepackage{caption}

\geometry{
    left=15mm,
    right=15mm,
    top=20mm,
    bottom=20mm,
}

\title{Parametric Fitting of FRB Host Galaxies:\\A Selection Bias Analysis}
\author{}
\date{\today}

\begin{document}
\maketitle
\vspace{-2em}
\tableofcontents
\newpage

""")

        # Introduction
        f.write(r"""\section{Introduction}
This report details our structural analysis of Fast Radio Burst (FRB) host galaxies using parametric light-profile fitting. The primary objective is to derive accurate disk inclination angles by de-convolving the intrinsic galaxy morphology from atmospheric and instrumental blurring. We utilize \texttt{GALFIT} to model the surface brightness of each FRB host galaxy across two configurations: a base model (No-PSF) and an instrument-corrected model (With-PSF). The resultant inclinations are then compared against background surveys to evaluate potential selection biases in FRB detection.

""")

        # Methodology
        f.write(r"""\section{Methodology}
Our fitting methodology prioritizes physical constraints to accurately retrieve the structural axis ratio, $b/a$. We enforce a Sersic index of $n=1$, corresponding to a purely exponential disk profile characteristic of spiral galaxies, provided this constraint does not cause a catastrophic surge in the reduced $\chi^2_\nu$ statistic. 

Initial guesses for \texttt{GALFIT} were derived from standard source extractor measurements. Following the extraction of the stabilized axis ratio ($b/a$), the true inclination angle ($i$) is calculated using the established Hubble formula, assuming a standard intrinsic disk thickness ($q_0 = 0.2$):

\begin{equation}
    \cos^2(i) = \frac{(b/a)^2 - q_0^2}{1 - q_0^2}
\end{equation}

Furthermore, we verified our Point Spread Functions (PSFs) by selectively picking stars using normalization, sky subtraction, and Moffat fitting. We found both the predicted FWHM and calculated them for different directions to average. The analytical FWHM was computed using the fitted Moffat parameters via the formula:

\begin{equation}
    FWHM = 2 \gamma \sqrt{2^{1/\alpha} - 1}
\end{equation}

\vspace{1em}
\noindent \href{https://drive.google.com/drive/my-drive}{\textcolor{blue}{\textbf{Note: All original FITS files, empirical PSFs, and supplemental plots are available in our Google Drive Repository.}}}

\clearpage
""")

        # PSFs section
        f.write(r"""\section{PSFs}
Below is the statistical summary of the Moffat profile parameters fitted to our empirical PSFs. The Moffat wing index $\alpha$ values (nominally 2.5--4.5 for ground-based seeing) are all within the physical range, confirming that the empirical PSFs are well-behaved and robust.

\begin{table}[H]
    \centering
    \begin{adjustbox}{max width=\textwidth}
    \begin{tabular}{l c c c c c c}
        \toprule
        \textbf{FRB} & \textbf{Avg FWHM} & \textbf{Moffat $\alpha$} & \textbf{Moffat $\gamma$} & \textbf{Analytical FWHM} & \textbf{Max Resid (\%)} \\
        \midrule
""")
        for index, row in df_psf.iterrows():
            f.write(f"        {row['FRB']} & {row['Avg_FWHM']:.2f} & {row['moffat_alpha']:.2f} & {row['moffat_gamma']:.2f} & {row['moffat_fwhm']:.2f} & {row['max_frac_resid_pct']:.2f}\\% \\\\\n")
        f.write(r"""        \bottomrule
    \end{tabular}
    \end{adjustbox}
    \caption{Empirical PSF FWHM and Moffat fit diagnostics.}
\end{table}

Below we show the 1D light magnitude profile across four directions (0$^\circ$, 45$^\circ$, 90$^\circ$, 135$^\circ$) for FRB~20190102C. The near-identical profiles across all directions confirm that the ePSF is highly symmetric.

\begin{figure}[H]
    \centering
    \includegraphics[width=0.8\textwidth]{psf_profile.png}
    \caption{1D light magnitude profiles across four position angles for the FRB~20190102C ePSF, demonstrating high radial symmetry.}
\end{figure}

\subsection{PSF Image Gallery}
""")
        used_psfs = []
        for index, row in df.iterrows():
            frb = row['frb_name']
            psf_candidates = glob.glob(f"Bias_Report/{frb}_with_psf_*psf*.png")
            if psf_candidates:
                used_psfs.append((frb, psf_candidates[0].replace('\\', '/')))
        
        # Use plain minipage grid with no figure float so LaTeX can break across pages naturally
        f.write("\\noindent\n")
        for i in range(0, len(used_psfs), 4):
            batch = used_psfs[i:i+4]
            width = 0.23
            f.write("\\noindent\n")
            for j, (frb, psf_path) in enumerate(batch):
                sep = "\\hfill" if j < len(batch) - 1 else ""
                f.write(f"""\\begin{{minipage}}{{{width}\\textwidth}}
\\centering
\\includegraphics[width=\\linewidth]{{{psf_path}}}\\\\[2pt]
{{\\small {frb}}}
\\end{{minipage}}{sep}\n""")
            f.write("\\vspace{0.5em}\n\n")

        f.write(r"""\clearpage
""")

        # Fits
        f.write(r"\section{Fits}" + "\n")
        
        for index, row in df.iterrows():
            frb = row['frb_name']
            f.write(rf"\subsection{{FRB {frb}}}" + "\n")
            
            # Simple line as requested: chi2nu, n, re
            meta_nopsf = f"No-PSF: $\\chi^2_\\nu$: {row['chi2nu_nopsf']:.3f}, $n$: {row['n_nopsf']:.2f}, $R_e$: {row['re_nopsf']:.2f}"
            meta_psf = f"With-PSF: $\\chi^2_\\nu$: {row['chi2nu_psf']:.3f}, $n$: {row['n_psf']:.2f}, $R_e$: {row['re_psf']:.2f}"
            
            f.write(f"{meta_nopsf} \\quad | \\quad {meta_psf}\n\n")

            f.write(f"""
\\begin{{figure}}[H]
    \\centering
    \\begin{{minipage}}[c]{{0.48\\textwidth}}
        \\centering
        \\includegraphics[width=\\linewidth]{{Bias_Report/{frb}_no_psf_image.png}}
    \\end{{minipage}}\\hfill
    \\begin{{minipage}}[c]{{0.48\\textwidth}}
        \\centering
        \\includegraphics[width=0.48\\linewidth]{{Bias_Report/{frb}_no_psf_model.png}}\\hfill
        \\includegraphics[width=0.48\\linewidth]{{Bias_Report/{frb}_no_psf_residual.png}}\\\\[0.04\\linewidth]
        \\includegraphics[width=0.48\\linewidth]{{Bias_Report/{frb}_with_psf_model.png}}\\hfill
        \\includegraphics[width=0.48\\linewidth]{{Bias_Report/{frb}_with_psf_residual.png}}
    \\end{{minipage}}
\\end{{figure}}
\\vspace{{0.5em}}
\\hrule
""")


        # Plots
        f.write(r"""\clearpage
\section{Plots}

\subsection{Inclination Angles Summary}

\begin{table}[H]
    \centering
    \begin{adjustbox}{max width=\textwidth}
    \begin{tabular}{l c c c c}
        \toprule
        \textbf{FRB} & \textbf{$b/a$ (No-PSF)} & \textbf{Inclination (No-PSF)} & \textbf{$b/a$ (With-PSF)} & \textbf{Inclination (With-PSF)} \\
        \midrule
""")
        for index, row in df.iterrows():
            frb = row['frb_name']
            f.write(f"        {frb} & {row['b_a_nopsf']:.2f} & {row['inc_nopsf']:.1f}$^\\circ$ & {row['b_a_psf']:.2f} & {row['inc_psf']:.1f}$^\\circ$ \\\\\n")
        f.write(r"""        \bottomrule
    \end{tabular}
    \end{adjustbox}
    \caption{Measured axis ratios and derived inclination angles for all FRB host galaxies.}
\end{table}

\subsection{Inclination Angle Bins}

\begin{figure}[H]
    \centering
    \begin{subfigure}{0.48\textwidth}
        \includegraphics[width=\linewidth]{plots_nopsf/bin_barchart.pdf}
        \caption{Bins (No-PSF)}
    \end{subfigure}\hfill
    \begin{subfigure}{0.48\textwidth}
        \includegraphics[width=\linewidth]{plots_psf/bin_barchart.pdf}
        \caption{Bins (With-PSF)}
    \end{subfigure}
    \caption{Distribution of FRB host galaxies across four inclination angle bins.}
\end{figure}

\subsection{CDF Bias Distributions}

\begin{figure}[H]
    \centering
    \begin{subfigure}{0.48\textwidth}
        \includegraphics[width=\linewidth]{plots_nopsf/CDF_bias.pdf}
        \caption{CDF Bias (No-PSF)}
    \end{subfigure}\hfill
    \begin{subfigure}{0.48\textwidth}
        \includegraphics[width=\linewidth]{plots_psf/CDF_bias.pdf}
        \caption{CDF Bias (With-PSF)}
    \end{subfigure}
    \caption{Cumulative density functions illustrating derived FRB host inclinations mapped against SDSS background probabilities.}
\end{figure}

\end{document}""")

        print("report.tex generation complete.")

if __name__ == "__main__":
    generate_report()
