import os
import numpy as np
import pandas as pd
from astropy.io import fits
from astropy.modeling.functional_models import Sersic2D, Moffat2D
from astropy.convolution import convolve

def hubble_q_from_inc(inc_deg, q0=0.2):
    if inc_deg == 90.0: return q0
    if inc_deg == 0.0: return 1.0
    inc_rad = np.radians(inc_deg)
    cos2 = np.cos(inc_rad)**2
    q = np.sqrt(cos2 * (1 - q0**2) + q0**2)
    return float(q)

def generate_mocks():
    out_dir = "tools/simulation/mock_data"
    os.makedirs(out_dir, exist_ok=True)
    
    re_list = [3, 5, 12, 25]  # pixels
    inc_list = [5, 15, 30, 45, 60, 80, 90] # degrees
    n_list = [1.0, 1.5, 2.0, 2.5, 3.0]
    
    # Fixed parameters
    PA = 45.0
    PIX_SCALE = 0.262 # arcsec/pix (Legacy Survey)
    SIZE = 100 # 100x100 cutout
    SKY_BKG = 100.0 # e-/pixel roughly
    READ_NOISE = 5.0 # e-
    EXPTIME = 1.0 # normalize to rates later if needed, but we'll work in e-
    
    # Generic Moffat PSF (beta=4.765, alpha=pixels) corresponding to 1.5 arcsec seeing
    # FWHM = 2 * alpha * sqrt(2**(1/beta) - 1)
    fwhm_arcsec = 1.2
    # FWHM = 2 * alpha * sqrt(2**(1/beta) - 1)
    fwhm_arcsec = 1.2
    
    # Load empirical PSF generated by PSFEx instead of a synthetic Moffat profile
    psf_img = fits.getdata('psfs/downsampled_psfs/20171020A_1x_psf.fits')
    psf_img = np.float32(psf_img / np.sum(psf_img))
    
    fits.writeto(os.path.join(out_dir, "mock_psf.fits"), np.float32(psf_img), overwrite=True)
    
    catalog = []
    
    count = 0
    for r in re_list:
        for i in inc_list:
            for n in n_list:
                frb_id = f"MOCK_{count:04d}"
                q = hubble_q_from_inc(i)
                # target magnitude corresponding to SNR ~ 10-50
                # total flux = amplitude * Re**2  ... roughly
                # just fix total flux to be a constant S/N scaler
                total_flux = 1e5 # e-
                
                # Sersic model
                y, x = np.mgrid[0:SIZE, 0:SIZE]
                sersic = Sersic2D(amplitude=1.0, r_eff=r, n=n, x_0=SIZE/2, y_0=SIZE/2, 
                                  ellip=1.0-q, theta=np.radians(PA))
                clean_img = sersic(x, y)
                # normalize flux
                clean_img *= (total_flux / np.sum(clean_img))
                
                # Broaden with PSF
                convolved = convolve(clean_img, psf_img, normalize_kernel=True)
                
                # Add background
                convolved_with_sky = convolved + SKY_BKG
                
                # Poisson noise
                noisy = np.random.poisson(convolved_with_sky).astype(float)
                
                # Read noise
                noisy += np.random.normal(0, READ_NOISE, noisy.shape)
                
                # Convert back to standard zero-background base by subtracting mean sky (perfect subtraction)
                flux_img = noisy - SKY_BKG
                # Sigma map: sqrt(N + read_noise^2)
                sigma_img = np.sqrt(np.clip(noisy, 1, None) + READ_NOISE**2)
                
                flux_path = os.path.join(out_dir, f"{frb_id}_flux.fits")
                sigma_path = os.path.join(out_dir, f"{frb_id}_sigma.fits")
                
                fits.writeto(flux_path, np.float32(flux_img), overwrite=True)
                fits.writeto(sigma_path, np.float32(sigma_img), overwrite=True)
                
                catalog.append({
                    "FRB": frb_id,
                    "true_re_pix": r,
                    "true_inc": i,
                    "true_n": n,
                    "true_pa": PA,
                    "true_q": q,
                    "flux_path": flux_path,
                    "sigma_path": sigma_path
                })
                count += 1
                
    cat_df = pd.DataFrame(catalog)
    cat_df.to_csv("tools/simulation/mock_catalog.csv", index=False)
    print(f"Generated {count} mock galaxies.")

if __name__ == "__main__":
    generate_mocks()
